// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes.proto
// Protobuf Java Version: 3.25.3
package bikes.grpc;

public interface BikeOrBuilder extends // @@protoc_insertion_point(interface_extends:Bike)
com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string locationId = 2;</code>
     * @return The locationId.
     */
    java.lang.String getLocationId();

    /**
     * <code>string locationId = 2;</code>
     * @return The bytes for locationId.
     */
    com.google.protobuf.ByteString getLocationIdBytes();

    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString getNameBytes();

    /**
     * <code>double rating = 4;</code>
     * @return The rating.
     */
    double getRating();

    /**
     * <code>int32 ratingCount = 5;</code>
     * @return The ratingCount.
     */
    int getRatingCount();

    /**
     * <code>double timeTravelled = 6;</code>
     * @return The timeTravelled.
     */
    double getTimeTravelled();

    /**
     * <code>int32 rentCount = 7;</code>
     * @return The rentCount.
     */
    int getRentCount();
}
