// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes.proto
// Protobuf Java Version: 3.25.3
package bikes.grpc;

public interface BikeListOrBuilder extends // @@protoc_insertion_point(interface_extends:BikeList)
com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Bike bikes = 1;</code>
     */
    java.util.List<bikes.grpc.Bike> getBikesList();

    /**
     * <code>repeated .Bike bikes = 1;</code>
     */
    bikes.grpc.Bike getBikes(int index);

    /**
     * <code>repeated .Bike bikes = 1;</code>
     */
    int getBikesCount();

    /**
     * <code>repeated .Bike bikes = 1;</code>
     */
    java.util.List<? extends bikes.grpc.BikeOrBuilder> getBikesOrBuilderList();

    /**
     * <code>repeated .Bike bikes = 1;</code>
     */
    bikes.grpc.BikeOrBuilder getBikesOrBuilder(int index);
}
