// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes.proto
// Protobuf Java Version: 3.25.3
package bikes.grpc;

public final class BikesOuterClass {

    private BikesOuterClass() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor internal_static_BikeRequest_descriptor;

    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_BikeRequest_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_Bike_descriptor;

    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_Bike_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_BikeList_descriptor;

    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_BikeList_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = { "\n\013bikes.proto\032\033google/protobuf/empty.pro" + "to\032\036google/protobuf/wrappers.proto\"~\n\013Bi" + "keRequest\022\n\n\002id\030\001 \001(\005\022\021\n\tstationId\030\002 \001(\t" + "\022\023\n\006rating\030\003 \001(\001H\000\210\001\001\022\034\n\017totalTimeRented" + "\030\004 \001(\003H\001\210\001\001B\t\n\007_ratingB\022\n\020_totalTimeRent" + "ed\"w\n\004Bike\022\n\n\002id\030\001 \001(\005\022\021\n\tstationId\030\002 \001(" + "\t\022\016\n\006rating\030\003 \001(\001\022\022\n\ntimesRated\030\004 \001(\005\022\023\n" + "\013timesRented\030\005 \001(\005\022\027\n\017totalTimeRented\030\006 " + "\001(\003\" \n\010BikeList\022\024\n\005bikes\030\001 \003(\0132\005.Bike2\230\004" + "\n\005Bikes\022/\n\014GetAllStream\022\026.google.protobu" + "f.Empty\032\005.Bike0\001\022+\n\006GetAll\022\026.google.prot" + "obuf.Empty\032\t.BikeList\022<\n\023GetByLocationSt" + "ream\022\034.google.protobuf.StringValue\032\005.Bik" + "e0\001\0228\n\rGetByLocation\022\034.google.protobuf.S" + "tringValue\032\t.BikeList\022-\n\007GetById\022\033.googl" + "e.protobuf.Int32Value\032\005.Bike\022!\n\nUpdateBy" + "Id\022\014.BikeRequest\032\005.Bike\022\035\n\006Create\022\014.Bike" + "Request\032\005.Bike\022A\n\nDeleteById\022\033.google.pr" + "otobuf.Int32Value\032\026.google.protobuf.Empt" + "y\022;\n\tDeleteAll\022\026.google.protobuf.Empty\032\026" + ".google.protobuf.Empty\022H\n\020DeleteByLocati" + "on\022\034.google.protobuf.StringValue\032\026.googl" + "e.protobuf.EmptyB\016\n\nbikes.grpcP\001b\006proto3" };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] { com.google.protobuf.EmptyProto.getDescriptor(), com.google.protobuf.WrappersProto.getDescriptor() });
        internal_static_BikeRequest_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_BikeRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_BikeRequest_descriptor, new java.lang.String[] { "Id", "StationId", "Rating", "TotalTimeRented" });
        internal_static_Bike_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_Bike_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_Bike_descriptor, new java.lang.String[] { "Id", "StationId", "Rating", "TimesRated", "TimesRented", "TotalTimeRented" });
        internal_static_BikeList_descriptor = getDescriptor().getMessageTypes().get(2);
        internal_static_BikeList_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_BikeList_descriptor, new java.lang.String[] { "Bikes" });
        com.google.protobuf.EmptyProto.getDescriptor();
        com.google.protobuf.WrappersProto.getDescriptor();
    }
    // @@protoc_insertion_point(outer_class_scope)
}
