// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes.proto
// Protobuf Java Version: 3.25.3
package bikes.grpc;

public interface BikeUpdateRatingRequestOrBuilder extends // @@protoc_insertion_point(interface_extends:BikeUpdateRatingRequest)
com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>double rating = 2;</code>
     * @return The rating.
     */
    double getRating();
}
