// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes.proto
// Protobuf Java Version: 3.25.3
package bikes.grpc;

/**
 * Protobuf type {@code BikeUpdateRatingRequest}
 */
public final class BikeUpdateRatingRequest extends com.google.protobuf.GeneratedMessageV3 implements // @@protoc_insertion_point(message_implements:BikeUpdateRatingRequest)
BikeUpdateRatingRequestOrBuilder {

    private static final long serialVersionUID = 0L;

    // Use BikeUpdateRatingRequest.newBuilder() to construct.
    private BikeUpdateRatingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private BikeUpdateRatingRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({ "unused" })
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
        return new BikeUpdateRatingRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return bikes.grpc.BikesOuterClass.internal_static_BikeUpdateRatingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return bikes.grpc.BikesOuterClass.internal_static_BikeUpdateRatingRequest_fieldAccessorTable.ensureFieldAccessorsInitialized(bikes.grpc.BikeUpdateRatingRequest.class, bikes.grpc.BikeUpdateRatingRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;

    private int id_ = 0;

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
        return id_;
    }

    public static final int RATING_FIELD_NUMBER = 2;

    private double rating_ = 0D;

    /**
     * <code>double rating = 2;</code>
     * @return The rating.
     */
    @java.lang.Override
    public double getRating() {
        return rating_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (id_ != 0) {
            output.writeInt32(1, id_);
        }
        if (java.lang.Double.doubleToRawLongBits(rating_) != 0) {
            output.writeDouble(2, rating_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        size = 0;
        if (id_ != 0) {
            size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, id_);
        }
        if (java.lang.Double.doubleToRawLongBits(rating_) != 0) {
            size += com.google.protobuf.CodedOutputStream.computeDoubleSize(2, rating_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof bikes.grpc.BikeUpdateRatingRequest)) {
            return super.equals(obj);
        }
        bikes.grpc.BikeUpdateRatingRequest other = (bikes.grpc.BikeUpdateRatingRequest) obj;
        if (getId() != other.getId())
            return false;
        if (java.lang.Double.doubleToLongBits(getRating()) != java.lang.Double.doubleToLongBits(other.getRating()))
            return false;
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (37 * hash) + RATING_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getRating()));
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static bikes.grpc.BikeUpdateRatingRequest parseFrom(java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static bikes.grpc.BikeUpdateRatingRequest parseFrom(java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static bikes.grpc.BikeUpdateRatingRequest parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static bikes.grpc.BikeUpdateRatingRequest parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static bikes.grpc.BikeUpdateRatingRequest parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static bikes.grpc.BikeUpdateRatingRequest parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static bikes.grpc.BikeUpdateRatingRequest parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static bikes.grpc.BikeUpdateRatingRequest parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static bikes.grpc.BikeUpdateRatingRequest parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static bikes.grpc.BikeUpdateRatingRequest parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static bikes.grpc.BikeUpdateRatingRequest parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static bikes.grpc.BikeUpdateRatingRequest parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(bikes.grpc.BikeUpdateRatingRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code BikeUpdateRatingRequest}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements // @@protoc_insertion_point(builder_implements:BikeUpdateRatingRequest)
    bikes.grpc.BikeUpdateRatingRequestOrBuilder {

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return bikes.grpc.BikesOuterClass.internal_static_BikeUpdateRatingRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return bikes.grpc.BikesOuterClass.internal_static_BikeUpdateRatingRequest_fieldAccessorTable.ensureFieldAccessorsInitialized(bikes.grpc.BikeUpdateRatingRequest.class, bikes.grpc.BikeUpdateRatingRequest.Builder.class);
        }

        // Construct using bikes.grpc.BikeUpdateRatingRequest.newBuilder()
        private Builder() {
        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            id_ = 0;
            rating_ = 0D;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return bikes.grpc.BikesOuterClass.internal_static_BikeUpdateRatingRequest_descriptor;
        }

        @java.lang.Override
        public bikes.grpc.BikeUpdateRatingRequest getDefaultInstanceForType() {
            return bikes.grpc.BikeUpdateRatingRequest.getDefaultInstance();
        }

        @java.lang.Override
        public bikes.grpc.BikeUpdateRatingRequest build() {
            bikes.grpc.BikeUpdateRatingRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public bikes.grpc.BikeUpdateRatingRequest buildPartial() {
            bikes.grpc.BikeUpdateRatingRequest result = new bikes.grpc.BikeUpdateRatingRequest(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(bikes.grpc.BikeUpdateRatingRequest result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.id_ = id_;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.rating_ = rating_;
            }
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof bikes.grpc.BikeUpdateRatingRequest) {
                return mergeFrom((bikes.grpc.BikeUpdateRatingRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(bikes.grpc.BikeUpdateRatingRequest other) {
            if (other == bikes.grpc.BikeUpdateRatingRequest.getDefaultInstance())
                return this;
            if (other.getId() != 0) {
                setId(other.getId());
            }
            if (other.getRating() != 0D) {
                setRating(other.getRating());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch(tag) {
                        case 0:
                            done = true;
                            break;
                        case 8:
                            {
                                id_ = input.readInt32();
                                bitField0_ |= 0x00000001;
                                break;
                            }
                        // case 8
                        case 17:
                            {
                                rating_ = input.readDouble();
                                bitField0_ |= 0x00000002;
                                break;
                            }
                        // case 17
                        default:
                            {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    // was an endgroup tag
                                    done = true;
                                }
                                break;
                            }
                    }
                    // switch (tag)
                }
                // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            }
            // finally
            return this;
        }

        private int bitField0_;

        private int id_;

        /**
         * <code>int32 id = 1;</code>
         * @return The id.
         */
        @java.lang.Override
        public int getId() {
            return id_;
        }

        /**
         * <code>int32 id = 1;</code>
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(int value) {
            id_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>int32 id = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearId() {
            bitField0_ = (bitField0_ & ~0x00000001);
            id_ = 0;
            onChanged();
            return this;
        }

        private double rating_;

        /**
         * <code>double rating = 2;</code>
         * @return The rating.
         */
        @java.lang.Override
        public double getRating() {
            return rating_;
        }

        /**
         * <code>double rating = 2;</code>
         * @param value The rating to set.
         * @return This builder for chaining.
         */
        public Builder setRating(double value) {
            rating_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>double rating = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearRating() {
            bitField0_ = (bitField0_ & ~0x00000002);
            rating_ = 0D;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }
        // @@protoc_insertion_point(builder_scope:BikeUpdateRatingRequest)
    }

    // @@protoc_insertion_point(class_scope:BikeUpdateRatingRequest)
    private static final bikes.grpc.BikeUpdateRatingRequest DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new bikes.grpc.BikeUpdateRatingRequest();
    }

    public static bikes.grpc.BikeUpdateRatingRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BikeUpdateRatingRequest> PARSER = new com.google.protobuf.AbstractParser<BikeUpdateRatingRequest>() {

        @java.lang.Override
        public BikeUpdateRatingRequest parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<BikeUpdateRatingRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BikeUpdateRatingRequest> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public bikes.grpc.BikeUpdateRatingRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
