// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes.proto
// Protobuf Java Version: 3.25.3
package bikes.grpc;

public interface BikeOrBuilder extends // @@protoc_insertion_point(interface_extends:Bike)
com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string stationId = 2;</code>
     * @return The stationId.
     */
    java.lang.String getStationId();

    /**
     * <code>string stationId = 2;</code>
     * @return The bytes for stationId.
     */
    com.google.protobuf.ByteString getStationIdBytes();

    /**
     * <code>double rating = 3;</code>
     * @return The rating.
     */
    double getRating();

    /**
     * <code>int32 timesRated = 4;</code>
     * @return The timesRated.
     */
    int getTimesRated();

    /**
     * <code>int32 timesRented = 5;</code>
     * @return The timesRented.
     */
    int getTimesRented();

    /**
     * <code>int64 totalTimeRented = 6;</code>
     * @return The totalTimeRented.
     */
    long getTotalTimeRented();
}
