// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes.proto
// Protobuf Java Version: 3.25.3
package bikes.grpc;

public interface BikeRequestOrBuilder extends // @@protoc_insertion_point(interface_extends:BikeRequest)
com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string stationId = 2;</code>
     * @return The stationId.
     */
    java.lang.String getStationId();

    /**
     * <code>string stationId = 2;</code>
     * @return The bytes for stationId.
     */
    com.google.protobuf.ByteString getStationIdBytes();

    /**
     * <code>optional double rating = 3;</code>
     * @return Whether the rating field is set.
     */
    boolean hasRating();

    /**
     * <code>optional double rating = 3;</code>
     * @return The rating.
     */
    double getRating();

    /**
     * <code>optional int64 totalTimeRented = 4;</code>
     * @return Whether the totalTimeRented field is set.
     */
    boolean hasTotalTimeRented();

    /**
     * <code>optional int64 totalTimeRented = 4;</code>
     * @return The totalTimeRented.
     */
    long getTotalTimeRented();
}
