// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes.proto
// Protobuf Java Version: 3.25.3
package bikes.grpc;

/**
 * Protobuf type {@code Bike}
 */
public final class Bike extends com.google.protobuf.GeneratedMessageV3 implements // @@protoc_insertion_point(message_implements:Bike)
BikeOrBuilder {

    private static final long serialVersionUID = 0L;

    // Use Bike.newBuilder() to construct.
    private Bike(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Bike() {
        locationId_ = "";
        name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({ "unused" })
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
        return new Bike();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return bikes.grpc.BikesOuterClass.internal_static_Bike_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return bikes.grpc.BikesOuterClass.internal_static_Bike_fieldAccessorTable.ensureFieldAccessorsInitialized(bikes.grpc.Bike.class, bikes.grpc.Bike.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;

    private int id_ = 0;

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
        return id_;
    }

    public static final int LOCATIONID_FIELD_NUMBER = 2;

    @SuppressWarnings("serial")
    private volatile java.lang.Object locationId_ = "";

    /**
     * <code>string locationId = 2;</code>
     * @return The locationId.
     */
    @java.lang.Override
    public java.lang.String getLocationId() {
        java.lang.Object ref = locationId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            locationId_ = s;
            return s;
        }
    }

    /**
     * <code>string locationId = 2;</code>
     * @return The bytes for locationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLocationIdBytes() {
        java.lang.Object ref = locationId_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            locationId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int NAME_FIELD_NUMBER = 3;

    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";

    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
        }
    }

    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            name_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int RATING_FIELD_NUMBER = 4;

    private double rating_ = 0D;

    /**
     * <code>double rating = 4;</code>
     * @return The rating.
     */
    @java.lang.Override
    public double getRating() {
        return rating_;
    }

    public static final int RATINGCOUNT_FIELD_NUMBER = 5;

    private int ratingCount_ = 0;

    /**
     * <code>int32 ratingCount = 5;</code>
     * @return The ratingCount.
     */
    @java.lang.Override
    public int getRatingCount() {
        return ratingCount_;
    }

    public static final int TIMETRAVELLED_FIELD_NUMBER = 6;

    private double timeTravelled_ = 0D;

    /**
     * <code>double timeTravelled = 6;</code>
     * @return The timeTravelled.
     */
    @java.lang.Override
    public double getTimeTravelled() {
        return timeTravelled_;
    }

    public static final int RENTCOUNT_FIELD_NUMBER = 7;

    private int rentCount_ = 0;

    /**
     * <code>int32 rentCount = 7;</code>
     * @return The rentCount.
     */
    @java.lang.Override
    public int getRentCount() {
        return rentCount_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (id_ != 0) {
            output.writeInt32(1, id_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(locationId_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, locationId_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
        }
        if (java.lang.Double.doubleToRawLongBits(rating_) != 0) {
            output.writeDouble(4, rating_);
        }
        if (ratingCount_ != 0) {
            output.writeInt32(5, ratingCount_);
        }
        if (java.lang.Double.doubleToRawLongBits(timeTravelled_) != 0) {
            output.writeDouble(6, timeTravelled_);
        }
        if (rentCount_ != 0) {
            output.writeInt32(7, rentCount_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        size = 0;
        if (id_ != 0) {
            size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, id_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(locationId_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, locationId_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
        }
        if (java.lang.Double.doubleToRawLongBits(rating_) != 0) {
            size += com.google.protobuf.CodedOutputStream.computeDoubleSize(4, rating_);
        }
        if (ratingCount_ != 0) {
            size += com.google.protobuf.CodedOutputStream.computeInt32Size(5, ratingCount_);
        }
        if (java.lang.Double.doubleToRawLongBits(timeTravelled_) != 0) {
            size += com.google.protobuf.CodedOutputStream.computeDoubleSize(6, timeTravelled_);
        }
        if (rentCount_ != 0) {
            size += com.google.protobuf.CodedOutputStream.computeInt32Size(7, rentCount_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof bikes.grpc.Bike)) {
            return super.equals(obj);
        }
        bikes.grpc.Bike other = (bikes.grpc.Bike) obj;
        if (getId() != other.getId())
            return false;
        if (!getLocationId().equals(other.getLocationId()))
            return false;
        if (!getName().equals(other.getName()))
            return false;
        if (java.lang.Double.doubleToLongBits(getRating()) != java.lang.Double.doubleToLongBits(other.getRating()))
            return false;
        if (getRatingCount() != other.getRatingCount())
            return false;
        if (java.lang.Double.doubleToLongBits(getTimeTravelled()) != java.lang.Double.doubleToLongBits(other.getTimeTravelled()))
            return false;
        if (getRentCount() != other.getRentCount())
            return false;
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (37 * hash) + LOCATIONID_FIELD_NUMBER;
        hash = (53 * hash) + getLocationId().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + RATING_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getRating()));
        hash = (37 * hash) + RATINGCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getRatingCount();
        hash = (37 * hash) + TIMETRAVELLED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getTimeTravelled()));
        hash = (37 * hash) + RENTCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getRentCount();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static bikes.grpc.Bike parseFrom(java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static bikes.grpc.Bike parseFrom(java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static bikes.grpc.Bike parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static bikes.grpc.Bike parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static bikes.grpc.Bike parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static bikes.grpc.Bike parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static bikes.grpc.Bike parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static bikes.grpc.Bike parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static bikes.grpc.Bike parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static bikes.grpc.Bike parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static bikes.grpc.Bike parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static bikes.grpc.Bike parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(bikes.grpc.Bike prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code Bike}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements // @@protoc_insertion_point(builder_implements:Bike)
    bikes.grpc.BikeOrBuilder {

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return bikes.grpc.BikesOuterClass.internal_static_Bike_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return bikes.grpc.BikesOuterClass.internal_static_Bike_fieldAccessorTable.ensureFieldAccessorsInitialized(bikes.grpc.Bike.class, bikes.grpc.Bike.Builder.class);
        }

        // Construct using bikes.grpc.Bike.newBuilder()
        private Builder() {
        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            id_ = 0;
            locationId_ = "";
            name_ = "";
            rating_ = 0D;
            ratingCount_ = 0;
            timeTravelled_ = 0D;
            rentCount_ = 0;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return bikes.grpc.BikesOuterClass.internal_static_Bike_descriptor;
        }

        @java.lang.Override
        public bikes.grpc.Bike getDefaultInstanceForType() {
            return bikes.grpc.Bike.getDefaultInstance();
        }

        @java.lang.Override
        public bikes.grpc.Bike build() {
            bikes.grpc.Bike result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public bikes.grpc.Bike buildPartial() {
            bikes.grpc.Bike result = new bikes.grpc.Bike(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(bikes.grpc.Bike result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.id_ = id_;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.locationId_ = locationId_;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.name_ = name_;
            }
            if (((from_bitField0_ & 0x00000008) != 0)) {
                result.rating_ = rating_;
            }
            if (((from_bitField0_ & 0x00000010) != 0)) {
                result.ratingCount_ = ratingCount_;
            }
            if (((from_bitField0_ & 0x00000020) != 0)) {
                result.timeTravelled_ = timeTravelled_;
            }
            if (((from_bitField0_ & 0x00000040) != 0)) {
                result.rentCount_ = rentCount_;
            }
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof bikes.grpc.Bike) {
                return mergeFrom((bikes.grpc.Bike) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(bikes.grpc.Bike other) {
            if (other == bikes.grpc.Bike.getDefaultInstance())
                return this;
            if (other.getId() != 0) {
                setId(other.getId());
            }
            if (!other.getLocationId().isEmpty()) {
                locationId_ = other.locationId_;
                bitField0_ |= 0x00000002;
                onChanged();
            }
            if (!other.getName().isEmpty()) {
                name_ = other.name_;
                bitField0_ |= 0x00000004;
                onChanged();
            }
            if (other.getRating() != 0D) {
                setRating(other.getRating());
            }
            if (other.getRatingCount() != 0) {
                setRatingCount(other.getRatingCount());
            }
            if (other.getTimeTravelled() != 0D) {
                setTimeTravelled(other.getTimeTravelled());
            }
            if (other.getRentCount() != 0) {
                setRentCount(other.getRentCount());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch(tag) {
                        case 0:
                            done = true;
                            break;
                        case 8:
                            {
                                id_ = input.readInt32();
                                bitField0_ |= 0x00000001;
                                break;
                            }
                        // case 8
                        case 18:
                            {
                                locationId_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000002;
                                break;
                            }
                        // case 18
                        case 26:
                            {
                                name_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000004;
                                break;
                            }
                        // case 26
                        case 33:
                            {
                                rating_ = input.readDouble();
                                bitField0_ |= 0x00000008;
                                break;
                            }
                        // case 33
                        case 40:
                            {
                                ratingCount_ = input.readInt32();
                                bitField0_ |= 0x00000010;
                                break;
                            }
                        // case 40
                        case 49:
                            {
                                timeTravelled_ = input.readDouble();
                                bitField0_ |= 0x00000020;
                                break;
                            }
                        // case 49
                        case 56:
                            {
                                rentCount_ = input.readInt32();
                                bitField0_ |= 0x00000040;
                                break;
                            }
                        // case 56
                        default:
                            {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    // was an endgroup tag
                                    done = true;
                                }
                                break;
                            }
                    }
                    // switch (tag)
                }
                // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            }
            // finally
            return this;
        }

        private int bitField0_;

        private int id_;

        /**
         * <code>int32 id = 1;</code>
         * @return The id.
         */
        @java.lang.Override
        public int getId() {
            return id_;
        }

        /**
         * <code>int32 id = 1;</code>
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(int value) {
            id_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>int32 id = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearId() {
            bitField0_ = (bitField0_ & ~0x00000001);
            id_ = 0;
            onChanged();
            return this;
        }

        private java.lang.Object locationId_ = "";

        /**
         * <code>string locationId = 2;</code>
         * @return The locationId.
         */
        public java.lang.String getLocationId() {
            java.lang.Object ref = locationId_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                locationId_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string locationId = 2;</code>
         * @return The bytes for locationId.
         */
        public com.google.protobuf.ByteString getLocationIdBytes() {
            java.lang.Object ref = locationId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                locationId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string locationId = 2;</code>
         * @param value The locationId to set.
         * @return This builder for chaining.
         */
        public Builder setLocationId(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            locationId_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>string locationId = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearLocationId() {
            locationId_ = getDefaultInstance().getLocationId();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }

        /**
         * <code>string locationId = 2;</code>
         * @param value The bytes for locationId to set.
         * @return This builder for chaining.
         */
        public Builder setLocationIdBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            locationId_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        private java.lang.Object name_ = "";

        /**
         * <code>string name = 3;</code>
         * @return The name.
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string name = 3;</code>
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string name = 3;</code>
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            name_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>string name = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearName() {
            name_ = getDefaultInstance().getName();
            bitField0_ = (bitField0_ & ~0x00000004);
            onChanged();
            return this;
        }

        /**
         * <code>string name = 3;</code>
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            name_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        private double rating_;

        /**
         * <code>double rating = 4;</code>
         * @return The rating.
         */
        @java.lang.Override
        public double getRating() {
            return rating_;
        }

        /**
         * <code>double rating = 4;</code>
         * @param value The rating to set.
         * @return This builder for chaining.
         */
        public Builder setRating(double value) {
            rating_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <code>double rating = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearRating() {
            bitField0_ = (bitField0_ & ~0x00000008);
            rating_ = 0D;
            onChanged();
            return this;
        }

        private int ratingCount_;

        /**
         * <code>int32 ratingCount = 5;</code>
         * @return The ratingCount.
         */
        @java.lang.Override
        public int getRatingCount() {
            return ratingCount_;
        }

        /**
         * <code>int32 ratingCount = 5;</code>
         * @param value The ratingCount to set.
         * @return This builder for chaining.
         */
        public Builder setRatingCount(int value) {
            ratingCount_ = value;
            bitField0_ |= 0x00000010;
            onChanged();
            return this;
        }

        /**
         * <code>int32 ratingCount = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearRatingCount() {
            bitField0_ = (bitField0_ & ~0x00000010);
            ratingCount_ = 0;
            onChanged();
            return this;
        }

        private double timeTravelled_;

        /**
         * <code>double timeTravelled = 6;</code>
         * @return The timeTravelled.
         */
        @java.lang.Override
        public double getTimeTravelled() {
            return timeTravelled_;
        }

        /**
         * <code>double timeTravelled = 6;</code>
         * @param value The timeTravelled to set.
         * @return This builder for chaining.
         */
        public Builder setTimeTravelled(double value) {
            timeTravelled_ = value;
            bitField0_ |= 0x00000020;
            onChanged();
            return this;
        }

        /**
         * <code>double timeTravelled = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearTimeTravelled() {
            bitField0_ = (bitField0_ & ~0x00000020);
            timeTravelled_ = 0D;
            onChanged();
            return this;
        }

        private int rentCount_;

        /**
         * <code>int32 rentCount = 7;</code>
         * @return The rentCount.
         */
        @java.lang.Override
        public int getRentCount() {
            return rentCount_;
        }

        /**
         * <code>int32 rentCount = 7;</code>
         * @param value The rentCount to set.
         * @return This builder for chaining.
         */
        public Builder setRentCount(int value) {
            rentCount_ = value;
            bitField0_ |= 0x00000040;
            onChanged();
            return this;
        }

        /**
         * <code>int32 rentCount = 7;</code>
         * @return This builder for chaining.
         */
        public Builder clearRentCount() {
            bitField0_ = (bitField0_ & ~0x00000040);
            rentCount_ = 0;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }
        // @@protoc_insertion_point(builder_scope:Bike)
    }

    // @@protoc_insertion_point(class_scope:Bike)
    private static final bikes.grpc.Bike DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new bikes.grpc.Bike();
    }

    public static bikes.grpc.Bike getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Bike> PARSER = new com.google.protobuf.AbstractParser<Bike>() {

        @java.lang.Override
        public Bike parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<Bike> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Bike> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public bikes.grpc.Bike getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
