// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes.proto
// Protobuf Java Version: 3.25.3
package bikes.grpc;

/**
 * Protobuf type {@code BikeRequest}
 */
public final class BikeRequest extends com.google.protobuf.GeneratedMessageV3 implements // @@protoc_insertion_point(message_implements:BikeRequest)
BikeRequestOrBuilder {

    private static final long serialVersionUID = 0L;

    // Use BikeRequest.newBuilder() to construct.
    private BikeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private BikeRequest() {
        stationId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({ "unused" })
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
        return new BikeRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return bikes.grpc.BikesOuterClass.internal_static_BikeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return bikes.grpc.BikesOuterClass.internal_static_BikeRequest_fieldAccessorTable.ensureFieldAccessorsInitialized(bikes.grpc.BikeRequest.class, bikes.grpc.BikeRequest.Builder.class);
    }

    private int bitField0_;

    public static final int ID_FIELD_NUMBER = 1;

    private int id_ = 0;

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
        return id_;
    }

    public static final int STATIONID_FIELD_NUMBER = 2;

    @SuppressWarnings("serial")
    private volatile java.lang.Object stationId_ = "";

    /**
     * <code>string stationId = 2;</code>
     * @return The stationId.
     */
    @java.lang.Override
    public java.lang.String getStationId() {
        java.lang.Object ref = stationId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            stationId_ = s;
            return s;
        }
    }

    /**
     * <code>string stationId = 2;</code>
     * @return The bytes for stationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getStationIdBytes() {
        java.lang.Object ref = stationId_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            stationId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int RATING_FIELD_NUMBER = 3;

    private double rating_ = 0D;

    /**
     * <code>optional double rating = 3;</code>
     * @return Whether the rating field is set.
     */
    @java.lang.Override
    public boolean hasRating() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>optional double rating = 3;</code>
     * @return The rating.
     */
    @java.lang.Override
    public double getRating() {
        return rating_;
    }

    public static final int TOTALTIMERENTED_FIELD_NUMBER = 4;

    private long totalTimeRented_ = 0L;

    /**
     * <code>optional int64 totalTimeRented = 4;</code>
     * @return Whether the totalTimeRented field is set.
     */
    @java.lang.Override
    public boolean hasTotalTimeRented() {
        return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>optional int64 totalTimeRented = 4;</code>
     * @return The totalTimeRented.
     */
    @java.lang.Override
    public long getTotalTimeRented() {
        return totalTimeRented_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (id_ != 0) {
            output.writeInt32(1, id_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stationId_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stationId_);
        }
        if (((bitField0_ & 0x00000001) != 0)) {
            output.writeDouble(3, rating_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
            output.writeInt64(4, totalTimeRented_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        size = 0;
        if (id_ != 0) {
            size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, id_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stationId_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stationId_);
        }
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream.computeDoubleSize(3, rating_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
            size += com.google.protobuf.CodedOutputStream.computeInt64Size(4, totalTimeRented_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof bikes.grpc.BikeRequest)) {
            return super.equals(obj);
        }
        bikes.grpc.BikeRequest other = (bikes.grpc.BikeRequest) obj;
        if (getId() != other.getId())
            return false;
        if (!getStationId().equals(other.getStationId()))
            return false;
        if (hasRating() != other.hasRating())
            return false;
        if (hasRating()) {
            if (java.lang.Double.doubleToLongBits(getRating()) != java.lang.Double.doubleToLongBits(other.getRating()))
                return false;
        }
        if (hasTotalTimeRented() != other.hasTotalTimeRented())
            return false;
        if (hasTotalTimeRented()) {
            if (getTotalTimeRented() != other.getTotalTimeRented())
                return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (37 * hash) + STATIONID_FIELD_NUMBER;
        hash = (53 * hash) + getStationId().hashCode();
        if (hasRating()) {
            hash = (37 * hash) + RATING_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getRating()));
        }
        if (hasTotalTimeRented()) {
            hash = (37 * hash) + TOTALTIMERENTED_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getTotalTimeRented());
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static bikes.grpc.BikeRequest parseFrom(java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static bikes.grpc.BikeRequest parseFrom(java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static bikes.grpc.BikeRequest parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static bikes.grpc.BikeRequest parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static bikes.grpc.BikeRequest parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static bikes.grpc.BikeRequest parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static bikes.grpc.BikeRequest parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static bikes.grpc.BikeRequest parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static bikes.grpc.BikeRequest parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static bikes.grpc.BikeRequest parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static bikes.grpc.BikeRequest parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static bikes.grpc.BikeRequest parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(bikes.grpc.BikeRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code BikeRequest}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements // @@protoc_insertion_point(builder_implements:BikeRequest)
    bikes.grpc.BikeRequestOrBuilder {

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return bikes.grpc.BikesOuterClass.internal_static_BikeRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return bikes.grpc.BikesOuterClass.internal_static_BikeRequest_fieldAccessorTable.ensureFieldAccessorsInitialized(bikes.grpc.BikeRequest.class, bikes.grpc.BikeRequest.Builder.class);
        }

        // Construct using bikes.grpc.BikeRequest.newBuilder()
        private Builder() {
        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            id_ = 0;
            stationId_ = "";
            rating_ = 0D;
            totalTimeRented_ = 0L;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return bikes.grpc.BikesOuterClass.internal_static_BikeRequest_descriptor;
        }

        @java.lang.Override
        public bikes.grpc.BikeRequest getDefaultInstanceForType() {
            return bikes.grpc.BikeRequest.getDefaultInstance();
        }

        @java.lang.Override
        public bikes.grpc.BikeRequest build() {
            bikes.grpc.BikeRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public bikes.grpc.BikeRequest buildPartial() {
            bikes.grpc.BikeRequest result = new bikes.grpc.BikeRequest(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(bikes.grpc.BikeRequest result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.id_ = id_;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.stationId_ = stationId_;
            }
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.rating_ = rating_;
                to_bitField0_ |= 0x00000001;
            }
            if (((from_bitField0_ & 0x00000008) != 0)) {
                result.totalTimeRented_ = totalTimeRented_;
                to_bitField0_ |= 0x00000002;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof bikes.grpc.BikeRequest) {
                return mergeFrom((bikes.grpc.BikeRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(bikes.grpc.BikeRequest other) {
            if (other == bikes.grpc.BikeRequest.getDefaultInstance())
                return this;
            if (other.getId() != 0) {
                setId(other.getId());
            }
            if (!other.getStationId().isEmpty()) {
                stationId_ = other.stationId_;
                bitField0_ |= 0x00000002;
                onChanged();
            }
            if (other.hasRating()) {
                setRating(other.getRating());
            }
            if (other.hasTotalTimeRented()) {
                setTotalTimeRented(other.getTotalTimeRented());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch(tag) {
                        case 0:
                            done = true;
                            break;
                        case 8:
                            {
                                id_ = input.readInt32();
                                bitField0_ |= 0x00000001;
                                break;
                            }
                        // case 8
                        case 18:
                            {
                                stationId_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000002;
                                break;
                            }
                        // case 18
                        case 25:
                            {
                                rating_ = input.readDouble();
                                bitField0_ |= 0x00000004;
                                break;
                            }
                        // case 25
                        case 32:
                            {
                                totalTimeRented_ = input.readInt64();
                                bitField0_ |= 0x00000008;
                                break;
                            }
                        // case 32
                        default:
                            {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    // was an endgroup tag
                                    done = true;
                                }
                                break;
                            }
                    }
                    // switch (tag)
                }
                // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            }
            // finally
            return this;
        }

        private int bitField0_;

        private int id_;

        /**
         * <code>int32 id = 1;</code>
         * @return The id.
         */
        @java.lang.Override
        public int getId() {
            return id_;
        }

        /**
         * <code>int32 id = 1;</code>
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(int value) {
            id_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>int32 id = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearId() {
            bitField0_ = (bitField0_ & ~0x00000001);
            id_ = 0;
            onChanged();
            return this;
        }

        private java.lang.Object stationId_ = "";

        /**
         * <code>string stationId = 2;</code>
         * @return The stationId.
         */
        public java.lang.String getStationId() {
            java.lang.Object ref = stationId_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                stationId_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string stationId = 2;</code>
         * @return The bytes for stationId.
         */
        public com.google.protobuf.ByteString getStationIdBytes() {
            java.lang.Object ref = stationId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                stationId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string stationId = 2;</code>
         * @param value The stationId to set.
         * @return This builder for chaining.
         */
        public Builder setStationId(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            stationId_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>string stationId = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearStationId() {
            stationId_ = getDefaultInstance().getStationId();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }

        /**
         * <code>string stationId = 2;</code>
         * @param value The bytes for stationId to set.
         * @return This builder for chaining.
         */
        public Builder setStationIdBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            stationId_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        private double rating_;

        /**
         * <code>optional double rating = 3;</code>
         * @return Whether the rating field is set.
         */
        @java.lang.Override
        public boolean hasRating() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>optional double rating = 3;</code>
         * @return The rating.
         */
        @java.lang.Override
        public double getRating() {
            return rating_;
        }

        /**
         * <code>optional double rating = 3;</code>
         * @param value The rating to set.
         * @return This builder for chaining.
         */
        public Builder setRating(double value) {
            rating_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>optional double rating = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearRating() {
            bitField0_ = (bitField0_ & ~0x00000004);
            rating_ = 0D;
            onChanged();
            return this;
        }

        private long totalTimeRented_;

        /**
         * <code>optional int64 totalTimeRented = 4;</code>
         * @return Whether the totalTimeRented field is set.
         */
        @java.lang.Override
        public boolean hasTotalTimeRented() {
            return ((bitField0_ & 0x00000008) != 0);
        }

        /**
         * <code>optional int64 totalTimeRented = 4;</code>
         * @return The totalTimeRented.
         */
        @java.lang.Override
        public long getTotalTimeRented() {
            return totalTimeRented_;
        }

        /**
         * <code>optional int64 totalTimeRented = 4;</code>
         * @param value The totalTimeRented to set.
         * @return This builder for chaining.
         */
        public Builder setTotalTimeRented(long value) {
            totalTimeRented_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <code>optional int64 totalTimeRented = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearTotalTimeRented() {
            bitField0_ = (bitField0_ & ~0x00000008);
            totalTimeRented_ = 0L;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }
        // @@protoc_insertion_point(builder_scope:BikeRequest)
    }

    // @@protoc_insertion_point(class_scope:BikeRequest)
    private static final bikes.grpc.BikeRequest DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new bikes.grpc.BikeRequest();
    }

    public static bikes.grpc.BikeRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BikeRequest> PARSER = new com.google.protobuf.AbstractParser<BikeRequest>() {

        @java.lang.Override
        public BikeRequest parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<BikeRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BikeRequest> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public bikes.grpc.BikeRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
