// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes.proto
// Protobuf Java Version: 3.25.3
package bikes.grpc;

public interface BikeRequestOrBuilder extends // @@protoc_insertion_point(interface_extends:BikeRequest)
com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string locationId = 2;</code>
     * @return The locationId.
     */
    java.lang.String getLocationId();

    /**
     * <code>string locationId = 2;</code>
     * @return The bytes for locationId.
     */
    com.google.protobuf.ByteString getLocationIdBytes();

    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString getNameBytes();
}
