// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes.proto
// Protobuf Java Version: 3.25.3
package bikes.grpc;

/**
 * Protobuf type {@code Bike}
 */
public final class Bike extends com.google.protobuf.GeneratedMessageV3 implements // @@protoc_insertion_point(message_implements:Bike)
BikeOrBuilder {

    private static final long serialVersionUID = 0L;

    // Use Bike.newBuilder() to construct.
    private Bike(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Bike() {
        stationId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({ "unused" })
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
        return new Bike();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return bikes.grpc.BikesOuterClass.internal_static_Bike_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return bikes.grpc.BikesOuterClass.internal_static_Bike_fieldAccessorTable.ensureFieldAccessorsInitialized(bikes.grpc.Bike.class, bikes.grpc.Bike.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;

    private int id_ = 0;

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
        return id_;
    }

    public static final int STATIONID_FIELD_NUMBER = 2;

    @SuppressWarnings("serial")
    private volatile java.lang.Object stationId_ = "";

    /**
     * <code>string stationId = 2;</code>
     * @return The stationId.
     */
    @java.lang.Override
    public java.lang.String getStationId() {
        java.lang.Object ref = stationId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            stationId_ = s;
            return s;
        }
    }

    /**
     * <code>string stationId = 2;</code>
     * @return The bytes for stationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getStationIdBytes() {
        java.lang.Object ref = stationId_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            stationId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int RATING_FIELD_NUMBER = 3;

    private double rating_ = 0D;

    /**
     * <code>double rating = 3;</code>
     * @return The rating.
     */
    @java.lang.Override
    public double getRating() {
        return rating_;
    }

    public static final int TIMESRATED_FIELD_NUMBER = 4;

    private int timesRated_ = 0;

    /**
     * <code>int32 timesRated = 4;</code>
     * @return The timesRated.
     */
    @java.lang.Override
    public int getTimesRated() {
        return timesRated_;
    }

    public static final int TIMESRENTED_FIELD_NUMBER = 5;

    private int timesRented_ = 0;

    /**
     * <code>int32 timesRented = 5;</code>
     * @return The timesRented.
     */
    @java.lang.Override
    public int getTimesRented() {
        return timesRented_;
    }

    public static final int TOTALTIMERENTED_FIELD_NUMBER = 6;

    private long totalTimeRented_ = 0L;

    /**
     * <code>int64 totalTimeRented = 6;</code>
     * @return The totalTimeRented.
     */
    @java.lang.Override
    public long getTotalTimeRented() {
        return totalTimeRented_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (id_ != 0) {
            output.writeInt32(1, id_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stationId_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stationId_);
        }
        if (java.lang.Double.doubleToRawLongBits(rating_) != 0) {
            output.writeDouble(3, rating_);
        }
        if (timesRated_ != 0) {
            output.writeInt32(4, timesRated_);
        }
        if (timesRented_ != 0) {
            output.writeInt32(5, timesRented_);
        }
        if (totalTimeRented_ != 0L) {
            output.writeInt64(6, totalTimeRented_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        size = 0;
        if (id_ != 0) {
            size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, id_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stationId_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stationId_);
        }
        if (java.lang.Double.doubleToRawLongBits(rating_) != 0) {
            size += com.google.protobuf.CodedOutputStream.computeDoubleSize(3, rating_);
        }
        if (timesRated_ != 0) {
            size += com.google.protobuf.CodedOutputStream.computeInt32Size(4, timesRated_);
        }
        if (timesRented_ != 0) {
            size += com.google.protobuf.CodedOutputStream.computeInt32Size(5, timesRented_);
        }
        if (totalTimeRented_ != 0L) {
            size += com.google.protobuf.CodedOutputStream.computeInt64Size(6, totalTimeRented_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof bikes.grpc.Bike)) {
            return super.equals(obj);
        }
        bikes.grpc.Bike other = (bikes.grpc.Bike) obj;
        if (getId() != other.getId())
            return false;
        if (!getStationId().equals(other.getStationId()))
            return false;
        if (java.lang.Double.doubleToLongBits(getRating()) != java.lang.Double.doubleToLongBits(other.getRating()))
            return false;
        if (getTimesRated() != other.getTimesRated())
            return false;
        if (getTimesRented() != other.getTimesRented())
            return false;
        if (getTotalTimeRented() != other.getTotalTimeRented())
            return false;
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (37 * hash) + STATIONID_FIELD_NUMBER;
        hash = (53 * hash) + getStationId().hashCode();
        hash = (37 * hash) + RATING_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getRating()));
        hash = (37 * hash) + TIMESRATED_FIELD_NUMBER;
        hash = (53 * hash) + getTimesRated();
        hash = (37 * hash) + TIMESRENTED_FIELD_NUMBER;
        hash = (53 * hash) + getTimesRented();
        hash = (37 * hash) + TOTALTIMERENTED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getTotalTimeRented());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static bikes.grpc.Bike parseFrom(java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static bikes.grpc.Bike parseFrom(java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static bikes.grpc.Bike parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static bikes.grpc.Bike parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static bikes.grpc.Bike parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static bikes.grpc.Bike parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static bikes.grpc.Bike parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static bikes.grpc.Bike parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static bikes.grpc.Bike parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static bikes.grpc.Bike parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static bikes.grpc.Bike parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static bikes.grpc.Bike parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(bikes.grpc.Bike prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code Bike}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements // @@protoc_insertion_point(builder_implements:Bike)
    bikes.grpc.BikeOrBuilder {

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return bikes.grpc.BikesOuterClass.internal_static_Bike_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return bikes.grpc.BikesOuterClass.internal_static_Bike_fieldAccessorTable.ensureFieldAccessorsInitialized(bikes.grpc.Bike.class, bikes.grpc.Bike.Builder.class);
        }

        // Construct using bikes.grpc.Bike.newBuilder()
        private Builder() {
        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            id_ = 0;
            stationId_ = "";
            rating_ = 0D;
            timesRated_ = 0;
            timesRented_ = 0;
            totalTimeRented_ = 0L;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return bikes.grpc.BikesOuterClass.internal_static_Bike_descriptor;
        }

        @java.lang.Override
        public bikes.grpc.Bike getDefaultInstanceForType() {
            return bikes.grpc.Bike.getDefaultInstance();
        }

        @java.lang.Override
        public bikes.grpc.Bike build() {
            bikes.grpc.Bike result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public bikes.grpc.Bike buildPartial() {
            bikes.grpc.Bike result = new bikes.grpc.Bike(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(bikes.grpc.Bike result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.id_ = id_;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.stationId_ = stationId_;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.rating_ = rating_;
            }
            if (((from_bitField0_ & 0x00000008) != 0)) {
                result.timesRated_ = timesRated_;
            }
            if (((from_bitField0_ & 0x00000010) != 0)) {
                result.timesRented_ = timesRented_;
            }
            if (((from_bitField0_ & 0x00000020) != 0)) {
                result.totalTimeRented_ = totalTimeRented_;
            }
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof bikes.grpc.Bike) {
                return mergeFrom((bikes.grpc.Bike) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(bikes.grpc.Bike other) {
            if (other == bikes.grpc.Bike.getDefaultInstance())
                return this;
            if (other.getId() != 0) {
                setId(other.getId());
            }
            if (!other.getStationId().isEmpty()) {
                stationId_ = other.stationId_;
                bitField0_ |= 0x00000002;
                onChanged();
            }
            if (other.getRating() != 0D) {
                setRating(other.getRating());
            }
            if (other.getTimesRated() != 0) {
                setTimesRated(other.getTimesRated());
            }
            if (other.getTimesRented() != 0) {
                setTimesRented(other.getTimesRented());
            }
            if (other.getTotalTimeRented() != 0L) {
                setTotalTimeRented(other.getTotalTimeRented());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch(tag) {
                        case 0:
                            done = true;
                            break;
                        case 8:
                            {
                                id_ = input.readInt32();
                                bitField0_ |= 0x00000001;
                                break;
                            }
                        // case 8
                        case 18:
                            {
                                stationId_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000002;
                                break;
                            }
                        // case 18
                        case 25:
                            {
                                rating_ = input.readDouble();
                                bitField0_ |= 0x00000004;
                                break;
                            }
                        // case 25
                        case 32:
                            {
                                timesRated_ = input.readInt32();
                                bitField0_ |= 0x00000008;
                                break;
                            }
                        // case 32
                        case 40:
                            {
                                timesRented_ = input.readInt32();
                                bitField0_ |= 0x00000010;
                                break;
                            }
                        // case 40
                        case 48:
                            {
                                totalTimeRented_ = input.readInt64();
                                bitField0_ |= 0x00000020;
                                break;
                            }
                        // case 48
                        default:
                            {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    // was an endgroup tag
                                    done = true;
                                }
                                break;
                            }
                    }
                    // switch (tag)
                }
                // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            }
            // finally
            return this;
        }

        private int bitField0_;

        private int id_;

        /**
         * <code>int32 id = 1;</code>
         * @return The id.
         */
        @java.lang.Override
        public int getId() {
            return id_;
        }

        /**
         * <code>int32 id = 1;</code>
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(int value) {
            id_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>int32 id = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearId() {
            bitField0_ = (bitField0_ & ~0x00000001);
            id_ = 0;
            onChanged();
            return this;
        }

        private java.lang.Object stationId_ = "";

        /**
         * <code>string stationId = 2;</code>
         * @return The stationId.
         */
        public java.lang.String getStationId() {
            java.lang.Object ref = stationId_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                stationId_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string stationId = 2;</code>
         * @return The bytes for stationId.
         */
        public com.google.protobuf.ByteString getStationIdBytes() {
            java.lang.Object ref = stationId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                stationId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string stationId = 2;</code>
         * @param value The stationId to set.
         * @return This builder for chaining.
         */
        public Builder setStationId(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            stationId_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>string stationId = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearStationId() {
            stationId_ = getDefaultInstance().getStationId();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }

        /**
         * <code>string stationId = 2;</code>
         * @param value The bytes for stationId to set.
         * @return This builder for chaining.
         */
        public Builder setStationIdBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            stationId_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        private double rating_;

        /**
         * <code>double rating = 3;</code>
         * @return The rating.
         */
        @java.lang.Override
        public double getRating() {
            return rating_;
        }

        /**
         * <code>double rating = 3;</code>
         * @param value The rating to set.
         * @return This builder for chaining.
         */
        public Builder setRating(double value) {
            rating_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>double rating = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearRating() {
            bitField0_ = (bitField0_ & ~0x00000004);
            rating_ = 0D;
            onChanged();
            return this;
        }

        private int timesRated_;

        /**
         * <code>int32 timesRated = 4;</code>
         * @return The timesRated.
         */
        @java.lang.Override
        public int getTimesRated() {
            return timesRated_;
        }

        /**
         * <code>int32 timesRated = 4;</code>
         * @param value The timesRated to set.
         * @return This builder for chaining.
         */
        public Builder setTimesRated(int value) {
            timesRated_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <code>int32 timesRated = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearTimesRated() {
            bitField0_ = (bitField0_ & ~0x00000008);
            timesRated_ = 0;
            onChanged();
            return this;
        }

        private int timesRented_;

        /**
         * <code>int32 timesRented = 5;</code>
         * @return The timesRented.
         */
        @java.lang.Override
        public int getTimesRented() {
            return timesRented_;
        }

        /**
         * <code>int32 timesRented = 5;</code>
         * @param value The timesRented to set.
         * @return This builder for chaining.
         */
        public Builder setTimesRented(int value) {
            timesRented_ = value;
            bitField0_ |= 0x00000010;
            onChanged();
            return this;
        }

        /**
         * <code>int32 timesRented = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearTimesRented() {
            bitField0_ = (bitField0_ & ~0x00000010);
            timesRented_ = 0;
            onChanged();
            return this;
        }

        private long totalTimeRented_;

        /**
         * <code>int64 totalTimeRented = 6;</code>
         * @return The totalTimeRented.
         */
        @java.lang.Override
        public long getTotalTimeRented() {
            return totalTimeRented_;
        }

        /**
         * <code>int64 totalTimeRented = 6;</code>
         * @param value The totalTimeRented to set.
         * @return This builder for chaining.
         */
        public Builder setTotalTimeRented(long value) {
            totalTimeRented_ = value;
            bitField0_ |= 0x00000020;
            onChanged();
            return this;
        }

        /**
         * <code>int64 totalTimeRented = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearTotalTimeRented() {
            bitField0_ = (bitField0_ & ~0x00000020);
            totalTimeRented_ = 0L;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }
        // @@protoc_insertion_point(builder_scope:Bike)
    }

    // @@protoc_insertion_point(class_scope:Bike)
    private static final bikes.grpc.Bike DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new bikes.grpc.Bike();
    }

    public static bikes.grpc.Bike getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Bike> PARSER = new com.google.protobuf.AbstractParser<Bike>() {

        @java.lang.Override
        public Bike parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<Bike> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Bike> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public bikes.grpc.Bike getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
