name: CI
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: test 
      working-directory: services/bikes_service
      shell: bash
      run: mvn -B test

    - name: package
      shell: bash
      run: mvn -B package --file ./services/bikes_service/pom.xml